Pin pyyaml version
This is a workaround for the depreciation of the simple `yaml.load(f)` call, without which the following error occurs during an upgrade:

```
TypeError: load() missing 1 required positional argument: 'Loader'
```

Fix based on fastpages commit https://github.com/fastai/fastpages/commit/028122f9929d3fed7960ae80ac9dd68c24a165ba